/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package atlassports.api;

import atlassports.enums.EntityStatus;
import atlassports.model.dto.TenantDto;
import atlassports.model.dto.UpsertTenantDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import javax.annotation.processing.Generated;
import java.util.Optional;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-24T16:37:25.216838800+01:00[Europe/Skopje]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "Tenants", description = "Tenant management")
public interface TenantsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_TENANTS_GET = "/tenants";

    /**
     * GET /tenants : Get all tenants (Admin only)
     *
     * @param page     (optional, default to 0)
     * @param size     (optional, default to 20)
     * @param sort     (optional)
     * @param dateFrom Filter tenants created from this date (ISO 8601 format) (optional)
     * @param dateTo   Filter tenants created up to this date (ISO 8601 format) (optional)
     * @return List of tenants (status code 200)
     */
    @Operation(
            operationId = "tenantsGet",
            summary = "Get all tenants (Admin only)",
            tags = {"Tenants"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "List of tenants", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Page.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = TenantsApi.PATH_TENANTS_GET,
            produces = {"application/json"}
    )
    default ResponseEntity<Page<TenantDto>> tenantsGet(
            @ParameterObject Pageable pageable,
            @RequestParam(required = false) String searchQuery
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"size\" : 6, \"last\" : true, \"totalPages\" : 5, \"page\" : 0, \"content\" : [ null, null ], \"first\" : true, \"totalElements\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_TENANTS_POST = "/tenants";

    /**
     * POST /tenants : Create new tenant (Admin only)
     *
     * @param body (required)
     * @return Tenant created (status code 201)
     */
    @Operation(
            operationId = "tenantsPost",
            summary = "Create new tenant (Admin only)",
            tags = {"Tenants"},
            responses = {
                    @ApiResponse(responseCode = "201", description = "Tenant created", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = TenantsApi.PATH_TENANTS_POST,
            produces = {"application/json"},
            consumes = {"application/json"}
    )
    default ResponseEntity<TenantDto> tenantsPost(
            @Parameter(name = "body", description = "", required = true) @Valid @RequestBody UpsertTenantDto body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_TENANTS_TENANT_ID_GET = "/tenants/{tenantId}";

    /**
     * GET /tenants/{tenantId} : Get tenant details
     *
     * @param tenantId (required)
     * @return Tenant details (status code 200)
     */
    @Operation(
            operationId = "tenantsTenantIdGet",
            summary = "Get tenant details",
            tags = {"Tenants"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Tenant details", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = TenantsApi.PATH_TENANTS_TENANT_ID_GET,
            produces = {"application/json"}
    )
    default ResponseEntity<TenantDto> tenantsTenantIdGet(
            @NotNull @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("tenantId") Long tenantId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_TENANTS_TENANT_ID_PATCH = "/tenants/{tenantId}";

    /**
     * PATCH /tenants/{tenantId} : Update tenant
     *
     * @param tenantId (required)
     * @param body     (required)
     * @return Updated tenant (status code 200)
     */
    @Operation(
            operationId = "tenantsTenantIdPatch",
            summary = "Update tenant",
            tags = {"Tenants"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Updated tenant", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.PATCH,
            value = TenantsApi.PATH_TENANTS_TENANT_ID_PATCH,
            produces = {"application/json"},
            consumes = {"application/json"}
    )
    default ResponseEntity<TenantDto> tenantsTenantIdPatch(
            @NotNull @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("tenantId") Long tenantId,
            @Parameter(name = "body", description = "", required = true) @Valid @RequestBody UpsertTenantDto body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_TENANTS_TENANT_ID_STATUS_PATCH = "/tenants/{tenantId}/status";

    /**
     * PATCH /tenants/{tenantId}/status : Enable or disable tenant
     *
     * @param tenantId                          (required)
     * @param tenantsTenantIdStatusPatchRequest (required)
     * @return Tenant status updated (status code 200)
     */
    @Operation(
            operationId = "tenantsTenantIdStatusPatch",
            summary = "Enable or disable tenant",
            tags = {"Tenants"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Tenant status updated")
            }
    )
    @RequestMapping(
            method = RequestMethod.PATCH,
            value = TenantsApi.PATH_TENANTS_TENANT_ID_STATUS_PATCH,
            consumes = {"application/json"}
    )
    default ResponseEntity<TenantDto> tenantsTenantIdStatusPatch(
            @NotNull @Parameter(name = "tenantId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("tenantId") Long tenantId,
            @Parameter(name = "status", description = "", required = true) @Valid @RequestBody EntityStatus status
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
